/* AUTO-GENERATED synthetic demo snapshots — no internal data. Do not edit by hand. */
export const DEMO: Record<string, unknown> = {
  "/api/agents": {
    "agents": [
      {
        "agent_name": "A",
        "run_id": "r-27",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "done",
        "step": "awaiting merge approval",
        "context_pct": 52,
        "context_band": "nominal",
        "last_step_at": "2026-08-29T06:16:17.894Z",
        "minutes_since_step": 0,
        "source": "live",
        "steps_logged": 15,
        "today": {
          "steps": 4,
          "cost_usd": 0.8999999999999999,
          "cost_recorded": 2,
          "tokens_in": 35000,
          "tokens_in_recorded": 2,
          "tokens_out": 4100,
          "tokens_out_recorded": 2,
          "tokens_total": 39100,
          "tokens_total_recorded": 4
        }
      },
      {
        "agent_name": "B",
        "run_id": "r-28",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "build",
        "step": "fixing pagination bound",
        "context_pct": 79,
        "context_band": "warning",
        "last_step_at": "2026-08-29T06:16:17.894Z",
        "minutes_since_step": 0,
        "source": "live",
        "steps_logged": 13,
        "today": {
          "steps": 4,
          "cost_usd": 1.5699999999999998,
          "cost_recorded": 2,
          "tokens_in": 49800,
          "tokens_in_recorded": 2,
          "tokens_out": 5750,
          "tokens_out_recorded": 2,
          "tokens_total": 55550,
          "tokens_total_recorded": 4
        }
      },
      {
        "agent_name": "C",
        "run_id": "r-29",
        "claude_session_id": "sess_c40182",
        "model": "claude-opus-5",
        "ticket_key": "APP-150",
        "phase": "build",
        "step": "large template refactor",
        "context_pct": 94,
        "context_band": "handover",
        "last_step_at": "2026-08-29T06:16:17.894Z",
        "minutes_since_step": 0,
        "source": "live",
        "steps_logged": 1,
        "today": {
          "steps": 1,
          "cost_usd": 2.74,
          "cost_recorded": 1,
          "tokens_in": 68000,
          "tokens_in_recorded": 1,
          "tokens_out": 7900,
          "tokens_out_recorded": 1,
          "tokens_total": 75900,
          "tokens_total_recorded": 2
        }
      }
    ],
    "log_exists": true,
    "malformed_lines": 0,
    "log_path": "(static demo)"
  },
  "/api/gates": {
    "tickets": [
      {
        "ticket_key": "APP-137",
        "gates": [
          {
            "gate": "DoR",
            "verdict": "pass",
            "recorded": true,
            "ts": "2026-08-27T06:16:17.893Z",
            "by": "B",
            "note": null,
            "source": "live"
          },
          {
            "gate": "RG-TL",
            "verdict": "approved",
            "recorded": true,
            "ts": "2026-08-28T06:16:17.894Z",
            "by": "B",
            "note": null,
            "source": "live"
          },
          {
            "gate": "RG-Dev",
            "verdict": "approved",
            "recorded": true,
            "ts": "2026-08-28T06:16:17.894Z",
            "by": "B",
            "note": null,
            "source": "live"
          },
          {
            "gate": "RG-Test",
            "verdict": "pass",
            "recorded": true,
            "ts": "2026-08-29T06:16:17.894Z",
            "by": "B",
            "note": null,
            "source": "live"
          },
          {
            "gate": "RG-Ver",
            "verdict": "bounced",
            "recorded": true,
            "ts": "2026-08-29T06:16:17.894Z",
            "by": "B",
            "note": "S2: pagination drops the last row when total is an exact multiple of page size.",
            "source": "live"
          },
          {
            "gate": "RG-Sec",
            "verdict": "pending",
            "recorded": false,
            "ts": null,
            "by": null,
            "note": null
          },
          {
            "gate": "G4",
            "verdict": "pending",
            "recorded": false,
            "ts": null,
            "by": null,
            "note": null
          }
        ],
        "blocked": true,
        "blocking_gates": [
          "RG-Ver"
        ],
        "ready_to_merge": false,
        "pr_url": "https://github.com/example/app/pull/39",
        "ci_state": "success",
        "solution_commit": "f6e5d4c3b2a1",
        "steps": 13,
        "last_activity": "2026-08-29T06:16:17.894Z"
      },
      {
        "ticket_key": "APP-142",
        "gates": [
          {
            "gate": "DoR",
            "verdict": "pass",
            "recorded": true,
            "ts": "2026-08-27T06:16:17.893Z",
            "by": "A",
            "note": null,
            "source": "live"
          },
          {
            "gate": "RG-TL",
            "verdict": "approved",
            "recorded": true,
            "ts": "2026-08-27T06:16:17.893Z",
            "by": "A",
            "note": null,
            "source": "live"
          },
          {
            "gate": "RG-Dev",
            "verdict": "approved",
            "recorded": true,
            "ts": "2026-08-28T06:16:17.893Z",
            "by": "A",
            "note": null,
            "source": "live"
          },
          {
            "gate": "RG-Test",
            "verdict": "pass",
            "recorded": true,
            "ts": "2026-08-28T06:16:17.893Z",
            "by": "A",
            "note": null,
            "source": "live"
          },
          {
            "gate": "RG-Ver",
            "verdict": "pass",
            "recorded": true,
            "ts": "2026-08-28T06:16:17.893Z",
            "by": "A",
            "note": null,
            "source": "live"
          },
          {
            "gate": "RG-Sec",
            "verdict": "pass",
            "recorded": true,
            "ts": "2026-08-29T06:16:17.893Z",
            "by": "A",
            "note": null,
            "source": "live"
          },
          {
            "gate": "G4",
            "verdict": "pass",
            "recorded": true,
            "ts": "2026-08-29T06:16:17.893Z",
            "by": "A",
            "note": null,
            "source": "live"
          }
        ],
        "blocked": false,
        "blocking_gates": [],
        "ready_to_merge": true,
        "pr_url": "https://github.com/example/app/pull/42",
        "ci_state": "success",
        "solution_commit": "a1b2c3d4e5f6",
        "steps": 15,
        "last_activity": "2026-08-29T06:16:17.894Z"
      }
    ],
    "gate_order": [
      "DoR",
      "RG-TL",
      "RG-Dev",
      "RG-Test",
      "RG-Ver",
      "RG-Sec",
      "G4"
    ]
  },
  "/api/usage?days=14": {
    "series": [
      {
        "key": "2026-08-23",
        "steps": 2,
        "cost_usd": 1.4400000000000002,
        "cost_recorded": 2,
        "tokens_in": 42800,
        "tokens_in_recorded": 2,
        "tokens_out": 4040,
        "tokens_out_recorded": 2,
        "tokens_total": 46840,
        "tokens_total_recorded": 4
      },
      {
        "key": "2026-08-24",
        "steps": 2,
        "cost_usd": 1.28,
        "cost_recorded": 2,
        "tokens_in": 39300,
        "tokens_in_recorded": 2,
        "tokens_out": 3825,
        "tokens_out_recorded": 2,
        "tokens_total": 43125,
        "tokens_total_recorded": 4
      },
      {
        "key": "2026-08-25",
        "steps": 2,
        "cost_usd": 1.1199999999999999,
        "cost_recorded": 2,
        "tokens_in": 35800,
        "tokens_in_recorded": 2,
        "tokens_out": 3610,
        "tokens_out_recorded": 2,
        "tokens_total": 39410,
        "tokens_total_recorded": 4
      },
      {
        "key": "2026-08-26",
        "steps": 2,
        "cost_usd": 0.9600000000000001,
        "cost_recorded": 2,
        "tokens_in": 32300,
        "tokens_in_recorded": 2,
        "tokens_out": 3395,
        "tokens_out_recorded": 2,
        "tokens_total": 35695,
        "tokens_total_recorded": 4
      },
      {
        "key": "2026-08-27",
        "steps": 5,
        "cost_usd": 0.8,
        "cost_recorded": 2,
        "tokens_in": 28800,
        "tokens_in_recorded": 2,
        "tokens_out": 3180,
        "tokens_out_recorded": 2,
        "tokens_total": 31980,
        "tokens_total_recorded": 4
      },
      {
        "key": "2026-08-28",
        "steps": 7,
        "cost_usd": 0.64,
        "cost_recorded": 2,
        "tokens_in": 25300,
        "tokens_in_recorded": 2,
        "tokens_out": 2965,
        "tokens_out_recorded": 2,
        "tokens_total": 28265,
        "tokens_total_recorded": 4
      },
      {
        "key": "2026-08-29",
        "steps": 9,
        "cost_usd": 5.21,
        "cost_recorded": 5,
        "tokens_in": 152800,
        "tokens_in_recorded": 5,
        "tokens_out": 17750,
        "tokens_out_recorded": 5,
        "tokens_total": 170550,
        "tokens_total_recorded": 10
      }
    ],
    "byTicket": [
      {
        "key": "APP-142",
        "steps": 15,
        "cost_usd": 4.74,
        "cost_recorded": 8,
        "tokens_in": 157100,
        "tokens_in_recorded": 8,
        "tokens_out": 16430,
        "tokens_out_recorded": 8,
        "tokens_total": 173530,
        "tokens_total_recorded": 16
      },
      {
        "key": "APP-137",
        "steps": 13,
        "cost_usd": 3.9699999999999998,
        "cost_recorded": 8,
        "tokens_in": 132000,
        "tokens_in_recorded": 8,
        "tokens_out": 14435,
        "tokens_out_recorded": 8,
        "tokens_total": 146435,
        "tokens_total_recorded": 16
      },
      {
        "key": "APP-150",
        "steps": 1,
        "cost_usd": 2.74,
        "cost_recorded": 1,
        "tokens_in": 68000,
        "tokens_in_recorded": 1,
        "tokens_out": 7900,
        "tokens_out_recorded": 1,
        "tokens_total": 75900,
        "tokens_total_recorded": 2
      }
    ],
    "byAgent": [
      {
        "key": "A",
        "steps": 15,
        "cost_usd": 4.74,
        "cost_recorded": 8,
        "tokens_in": 157100,
        "tokens_in_recorded": 8,
        "tokens_out": 16430,
        "tokens_out_recorded": 8,
        "tokens_total": 173530,
        "tokens_total_recorded": 16
      },
      {
        "key": "B",
        "steps": 13,
        "cost_usd": 3.9699999999999998,
        "cost_recorded": 8,
        "tokens_in": 132000,
        "tokens_in_recorded": 8,
        "tokens_out": 14435,
        "tokens_out_recorded": 8,
        "tokens_total": 146435,
        "tokens_total_recorded": 16
      },
      {
        "key": "C",
        "steps": 1,
        "cost_usd": 2.74,
        "cost_recorded": 1,
        "tokens_in": 68000,
        "tokens_in_recorded": 1,
        "tokens_out": 7900,
        "tokens_out_recorded": 1,
        "tokens_total": 75900,
        "tokens_total_recorded": 2
      }
    ],
    "byModel": [
      {
        "key": "claude-opus-5",
        "steps": 29,
        "cost_usd": 11.450000000000001,
        "cost_recorded": 17,
        "tokens_in": 357100,
        "tokens_in_recorded": 17,
        "tokens_out": 38765,
        "tokens_out_recorded": 17,
        "tokens_total": 395865,
        "tokens_total_recorded": 34
      }
    ],
    "totals": {
      "steps": 29,
      "cost_usd": 11.450000000000001,
      "cost_recorded": 17,
      "tokens_in": 357100,
      "tokens_in_recorded": 17,
      "tokens_out": 38765,
      "tokens_out_recorded": 17,
      "tokens_total": 395865,
      "tokens_total_recorded": 34
    },
    "window_days": 14
  },
  "/api/runs?limit=500": {
    "rows": [
      {
        "ts": "2026-08-29T06:16:17.894Z",
        "run_id": "r-29",
        "agent_name": "C",
        "claude_session_id": "sess_c40182",
        "model": "claude-opus-5",
        "ticket_key": "APP-150",
        "phase": "build",
        "step": "large template refactor",
        "tokens_in": 68000,
        "tokens_out": 7900,
        "cost_usd": 2.74,
        "context_pct": 94,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.894Z",
        "run_id": "r-28",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "build",
        "step": "fixing pagination bound",
        "tokens_in": 41000,
        "tokens_out": 4600,
        "cost_usd": 1.38,
        "context_pct": 79,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.894Z",
        "run_id": "r-27",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "done",
        "step": "awaiting merge approval",
        "tokens_in": 22000,
        "tokens_out": 2500,
        "cost_usd": 0.61,
        "context_pct": 52,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.894Z",
        "run_id": "r-26",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-3",
        "step": "adversarial verify: off-by-one in pagination",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Ver",
        "verdict": "bounced",
        "note": "S2: pagination drops the last row when total is an exact multiple of page size.",
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.894Z",
        "run_id": "r-25",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "functional tests",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Test",
        "verdict": "pass",
        "note": null,
        "pr_url": "https://github.com/example/app/pull/39",
        "ci_state": "success",
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.893Z",
        "run_id": "r-21",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "PR",
        "step": "open pull request",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "G4",
        "verdict": "pass",
        "note": null,
        "pr_url": "https://github.com/example/app/pull/42",
        "ci_state": "success",
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.893Z",
        "run_id": "r-20",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "QA-4",
        "step": "security review",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Sec",
        "verdict": "pass",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.893Z",
        "run_id": "r-14",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 8800,
        "tokens_out": 1150,
        "cost_usd": 0.19,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.893Z",
        "run_id": "r-13",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 13000,
        "tokens_out": 1600,
        "cost_usd": 0.29,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.894Z",
        "run_id": "r-24",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "review",
        "step": "solution review",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Dev",
        "verdict": "approved",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.894Z",
        "run_id": "r-23",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "design",
        "step": "solution document",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-TL",
        "verdict": "approved",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": "f6e5d4c3b2a1",
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.893Z",
        "run_id": "r-19",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "QA-3",
        "step": "adversarial verify",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Ver",
        "verdict": "pass",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.893Z",
        "run_id": "r-18",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "QA-1",
        "step": "functional tests",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Test",
        "verdict": "pass",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.893Z",
        "run_id": "r-17",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "review",
        "step": "solution review",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Dev",
        "verdict": "approved",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.893Z",
        "run_id": "r-12",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 10200,
        "tokens_out": 1235,
        "cost_usd": 0.25,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.892Z",
        "run_id": "r-11",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 15100,
        "tokens_out": 1730,
        "cost_usd": 0.39,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-27T06:16:17.893Z",
        "run_id": "r-22",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "DoR",
        "step": "definition of ready",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "DoR",
        "verdict": "pass",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-27T06:16:17.893Z",
        "run_id": "r-16",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "design",
        "step": "solution document",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-TL",
        "verdict": "approved",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": "a1b2c3d4e5f6",
        "source": "live"
      },
      {
        "ts": "2026-08-27T06:16:17.893Z",
        "run_id": "r-15",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "DoR",
        "step": "definition of ready",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "DoR",
        "verdict": "pass",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-27T06:16:17.892Z",
        "run_id": "r-10",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 11600,
        "tokens_out": 1320,
        "cost_usd": 0.31,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-27T06:16:17.892Z",
        "run_id": "r-9",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 17200,
        "tokens_out": 1860,
        "cost_usd": 0.49,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-26T06:16:17.892Z",
        "run_id": "r-8",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 13000,
        "tokens_out": 1405,
        "cost_usd": 0.37,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-26T06:16:17.892Z",
        "run_id": "r-7",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 19300,
        "tokens_out": 1990,
        "cost_usd": 0.5900000000000001,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-25T06:16:17.892Z",
        "run_id": "r-6",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 14400,
        "tokens_out": 1490,
        "cost_usd": 0.43,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-25T06:16:17.892Z",
        "run_id": "r-5",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 21400,
        "tokens_out": 2120,
        "cost_usd": 0.69,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-24T06:16:17.891Z",
        "run_id": "r-4",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 15800,
        "tokens_out": 1575,
        "cost_usd": 0.49,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-24T06:16:17.891Z",
        "run_id": "r-3",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 23500,
        "tokens_out": 2250,
        "cost_usd": 0.79,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-23T06:16:17.891Z",
        "run_id": "r-2",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 17200,
        "tokens_out": 1660,
        "cost_usd": 0.55,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-23T06:16:17.876Z",
        "run_id": "r-1",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 25600,
        "tokens_out": 2380,
        "cost_usd": 0.8900000000000001,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      }
    ],
    "total": 29,
    "truncated": false,
    "malformed": 0,
    "log_exists": true
  },
  "/api/runs?limit=100": {
    "rows": [
      {
        "ts": "2026-08-29T06:16:17.894Z",
        "run_id": "r-29",
        "agent_name": "C",
        "claude_session_id": "sess_c40182",
        "model": "claude-opus-5",
        "ticket_key": "APP-150",
        "phase": "build",
        "step": "large template refactor",
        "tokens_in": 68000,
        "tokens_out": 7900,
        "cost_usd": 2.74,
        "context_pct": 94,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.894Z",
        "run_id": "r-28",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "build",
        "step": "fixing pagination bound",
        "tokens_in": 41000,
        "tokens_out": 4600,
        "cost_usd": 1.38,
        "context_pct": 79,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.894Z",
        "run_id": "r-27",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "done",
        "step": "awaiting merge approval",
        "tokens_in": 22000,
        "tokens_out": 2500,
        "cost_usd": 0.61,
        "context_pct": 52,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.894Z",
        "run_id": "r-26",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-3",
        "step": "adversarial verify: off-by-one in pagination",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Ver",
        "verdict": "bounced",
        "note": "S2: pagination drops the last row when total is an exact multiple of page size.",
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.894Z",
        "run_id": "r-25",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "functional tests",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Test",
        "verdict": "pass",
        "note": null,
        "pr_url": "https://github.com/example/app/pull/39",
        "ci_state": "success",
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.893Z",
        "run_id": "r-21",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "PR",
        "step": "open pull request",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "G4",
        "verdict": "pass",
        "note": null,
        "pr_url": "https://github.com/example/app/pull/42",
        "ci_state": "success",
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.893Z",
        "run_id": "r-20",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "QA-4",
        "step": "security review",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Sec",
        "verdict": "pass",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.893Z",
        "run_id": "r-14",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 8800,
        "tokens_out": 1150,
        "cost_usd": 0.19,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-29T06:16:17.893Z",
        "run_id": "r-13",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 13000,
        "tokens_out": 1600,
        "cost_usd": 0.29,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.894Z",
        "run_id": "r-24",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "review",
        "step": "solution review",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Dev",
        "verdict": "approved",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.894Z",
        "run_id": "r-23",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "design",
        "step": "solution document",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-TL",
        "verdict": "approved",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": "f6e5d4c3b2a1",
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.893Z",
        "run_id": "r-19",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "QA-3",
        "step": "adversarial verify",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Ver",
        "verdict": "pass",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.893Z",
        "run_id": "r-18",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "QA-1",
        "step": "functional tests",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Test",
        "verdict": "pass",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.893Z",
        "run_id": "r-17",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "review",
        "step": "solution review",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-Dev",
        "verdict": "approved",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.893Z",
        "run_id": "r-12",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 10200,
        "tokens_out": 1235,
        "cost_usd": 0.25,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-28T06:16:17.892Z",
        "run_id": "r-11",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 15100,
        "tokens_out": 1730,
        "cost_usd": 0.39,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-27T06:16:17.893Z",
        "run_id": "r-22",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "DoR",
        "step": "definition of ready",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "DoR",
        "verdict": "pass",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-27T06:16:17.893Z",
        "run_id": "r-16",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "design",
        "step": "solution document",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "RG-TL",
        "verdict": "approved",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": "a1b2c3d4e5f6",
        "source": "live"
      },
      {
        "ts": "2026-08-27T06:16:17.893Z",
        "run_id": "r-15",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "DoR",
        "step": "definition of ready",
        "tokens_in": null,
        "tokens_out": null,
        "cost_usd": null,
        "context_pct": null,
        "gate": "DoR",
        "verdict": "pass",
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-27T06:16:17.892Z",
        "run_id": "r-10",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 11600,
        "tokens_out": 1320,
        "cost_usd": 0.31,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-27T06:16:17.892Z",
        "run_id": "r-9",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 17200,
        "tokens_out": 1860,
        "cost_usd": 0.49,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-26T06:16:17.892Z",
        "run_id": "r-8",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 13000,
        "tokens_out": 1405,
        "cost_usd": 0.37,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-26T06:16:17.892Z",
        "run_id": "r-7",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 19300,
        "tokens_out": 1990,
        "cost_usd": 0.5900000000000001,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-25T06:16:17.892Z",
        "run_id": "r-6",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 14400,
        "tokens_out": 1490,
        "cost_usd": 0.43,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-25T06:16:17.892Z",
        "run_id": "r-5",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 21400,
        "tokens_out": 2120,
        "cost_usd": 0.69,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-24T06:16:17.891Z",
        "run_id": "r-4",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 15800,
        "tokens_out": 1575,
        "cost_usd": 0.49,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-24T06:16:17.891Z",
        "run_id": "r-3",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 23500,
        "tokens_out": 2250,
        "cost_usd": 0.79,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-23T06:16:17.891Z",
        "run_id": "r-2",
        "agent_name": "B",
        "claude_session_id": "sess_3b71de",
        "model": "claude-opus-5",
        "ticket_key": "APP-137",
        "phase": "QA-1",
        "step": "run regression suite",
        "tokens_in": 17200,
        "tokens_out": 1660,
        "cost_usd": 0.55,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      },
      {
        "ts": "2026-08-23T06:16:17.876Z",
        "run_id": "r-1",
        "agent_name": "A",
        "claude_session_id": "sess_9f2a4c",
        "model": "claude-opus-5",
        "ticket_key": "APP-142",
        "phase": "build",
        "step": "implement search filter",
        "tokens_in": 25600,
        "tokens_out": 2380,
        "cost_usd": 0.8900000000000001,
        "context_pct": null,
        "gate": null,
        "verdict": null,
        "note": null,
        "pr_url": null,
        "ci_state": null,
        "solution_commit": null,
        "source": "live"
      }
    ],
    "total": 29,
    "truncated": false,
    "malformed": 0,
    "log_exists": true
  },
  "/api/approvals": {
    "items": [
      {
        "request_id": "APP-137:RG-Ver",
        "ticket_key": "APP-137",
        "gate": "RG-Ver",
        "verdict": "bounced",
        "raised_at": "2026-08-29T06:16:17.894Z",
        "raised_by": "B",
        "note": "S2: pagination drops the last row when total is an exact multiple of page size.",
        "pr_url": "https://github.com/example/app/pull/39",
        "ci_state": "success",
        "solution_commit": "f6e5d4c3b2a1",
        "blocked": true,
        "blocking_gates": [
          "RG-Ver"
        ],
        "ready_to_merge": false,
        "decision": null
      }
    ],
    "decided": [],
    "gate_order": [
      "DoR",
      "RG-TL",
      "RG-Dev",
      "RG-Test",
      "RG-Ver",
      "RG-Sec",
      "G4"
    ]
  },
  "/api/config": {
    "log_path": "(static demo)",
    "jira_configured": false,
    "jira_project": null,
    "mail_configured": true,
    "reader": "StaticDemoReader"
  },
  "/api/settings": {
    "mail": {
      "host": "smtp.example.com",
      "port": 587,
      "security": "starttls",
      "username": "agent-control@example.com",
      "password_set": true,
      "from_name": "Agent Control",
      "from_email": "agent-control@example.com",
      "reply_to": null,
      "updated_at": "2026-08-27T09:12:00.000Z"
    },
    "mail_configured": true,
    "groups": [
      {
        "id": "grp_demo_platform",
        "name": "Platform approvers",
        "team": "Platform",
        "description": "Anyone who can clear a merge gate for the platform services.",
        "notify_events": ["approval.recorded"],
        "created_at": "2026-08-20T10:00:00.000Z",
        "updated_at": "2026-08-27T09:12:00.000Z"
      },
      {
        "id": "grp_demo_intake",
        "name": "Requirement intake",
        "team": "Product",
        "description": "Told when a new agent-eligible ticket is written.",
        "notify_events": ["requirement.created"],
        "created_at": "2026-08-22T11:30:00.000Z",
        "updated_at": "2026-08-22T11:30:00.000Z"
      }
    ],
    "users": [
      {
        "id": "usr_demo_1", "name": "Alex Fry", "email": "alex@example.com", "role": "approver",
        "group_id": "grp_demo_platform", "notify": true,
        "created_at": "2026-08-20T10:05:00.000Z", "updated_at": "2026-08-20T10:05:00.000Z"
      },
      {
        "id": "usr_demo_2", "name": "Priya Raman", "email": "priya@example.com", "role": "owner",
        "group_id": "grp_demo_platform", "notify": true,
        "created_at": "2026-08-20T10:06:00.000Z", "updated_at": "2026-08-26T14:41:00.000Z"
      },
      {
        "id": "usr_demo_3", "name": "Sam Okafor", "email": "sam@example.com", "role": "viewer",
        "group_id": "grp_demo_intake", "notify": false,
        "created_at": "2026-08-22T11:35:00.000Z", "updated_at": "2026-08-22T11:35:00.000Z"
      }
    ],
    "security_options": ["tls", "starttls", "none"],
    "roles": ["owner", "approver", "viewer"],
    "events": ["approval.recorded", "requirement.created"],
    "settings_path": "(static demo — nothing is stored)"
  }
};
